name: Continuous Integration
on:
  push:
    branches: [ main ]

jobs:
  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: | # This way we can run several commands
          npm start &
          sleep 2000
          npm test
